################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
spring:
 profiles: DES
 datasource:
  sqlScriptEncoding: UTF-8
  
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   backconfiguracion: STO-BACK-CONFIGURACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:9020
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---
################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
spring:
 profiles: LOCAL
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   backconfiguracion: STO-BACK-CONFIGURACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://localhost:9020
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---

################################################################################################################################
# Entorno para desarrollo WEBLOGIC
################################################################################################################################
spring:
 profiles: WEBLOGIC
 datasource:
  sqlScriptEncoding: UTF-8
  max-active: 5
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   backconfiguracion: STO-BACK-CONFIGURACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:7001
 server:
  context-paths:
   sto-front-configuracion: /sto-front-configuracion
   sto-front-autenticacion: /sto-front-autenticacion
   sto-gateway: /sto-gateway
   sto-front-administracion: /sto-front-administracion
   sto-eureka: /sto-eureka
   sto-back-configuracion: /sto-back-configuracion
   sto-server-configuracion: /sto-server-configuracion
   sto-back-autenticacion: /sto-back-autenticacion
   sto-back-administracion: /sto-back-administracion
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---

################################################################################################################################
# Entorno para desarrollo TOMCAT
################################################################################################################################
spring:
 profiles: TOMCAT
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   backconfiguracion: STO-BACK-CONFIGURACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:8001
 server:
  context-paths:
   sto-front-configuracion: /sto-front-configuracion
   sto-front-autenticacion: /sto-front-autenticacion
   sto-gateway: /sto-gateway
   sto-front-administracion: /sto-front-administracion
   sto-eureka: /sto-eureka
   sto-back-configuracion: /sto-back-configuracion
   sto-back-autenticacion: /sto-back-autenticacion
   sto-back-administracion: /sto-back-administracion
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

################################################################################################################################
# Entorno para desarrollo LOCAL (SPRING CLOUD GATEWAY y LOADBALANCER)
################################################################################################################################
spring:
 profiles: LOCAL-CLOUD-GATEWAY
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   backconfiguracion: STO-BACK-CONFIGURACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://localhost:9020
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---

################################################################################################################################
# Entorno para desarrollo WEBLOGIC (SPRING CLOUD GATEWAY y LOADBALANCER)
################################################################################################################################
spring:
 profiles: WEBLOGIC-CLOUD-GATEWAY
 datasource:
  sqlScriptEncoding: UTF-8
  max-active: 5
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   backconfiguracion: STO-BACK-CONFIGURACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:7001
 server:
  context-paths:
   sto-front-configuracion: /sto-front-configuracion
   sto-front-autenticacion: /sto-front-autenticacion
   sto-gateway: /sto-gateway
   sto-front-administracion: /sto-front-administracion
   sto-eureka: /sto-eureka
   sto-back-configuracion: /sto-back-configuracion
   sto-server-configuracion: /sto-server-configuracion
   sto-back-autenticacion: /sto-back-autenticacion
   sto-back-administracion: /sto-back-administracion
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
