################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
spring:
 profiles: DES
 datasource:
  sqlScriptEncoding: UTF-8
  
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:9020
 
#Configuraciones de seguridad
security:
 basic:
  enabled: false
 oauth2:
  client:
   clientId: fooClientId
   clientSecret: secret
   accessTokenUri: ${config.endpoint.backautenticacion}/auth/oauth/token
   userAuthorizationUri: ${config.endpoint.backautenticacion}/auth/oauth/authorize
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   jwt:
    key-value: 1234
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

---
################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
spring:
 profiles: LOCAL
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://localhost:9020 
 
#Configuraciones de seguridad
security:
 basic:
  enabled: false
 oauth2:
  client:
   clientId: fooClientId
   clientSecret: '{cipher}015d9f900e42352c30a084c8a5c8dd9860909876a31f8b0cb2b19e545d065cc8'
   accessTokenUri: ${config.endpoint.backautenticacion}/auth/oauth/token
   userAuthorizationUri: ${config.endpoint.backautenticacion}/auth/oauth/authorize
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true
