################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
spring:
 profiles: DES
 datasource:
  sqlScriptEncoding: UTF-8
  
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:9020
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

---
################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
spring:
 profiles: LOCAL
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://localhost:9020
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true

---

################################################################################################################################
# Entorno para desarrollo WEBLOGIC
################################################################################################################################
spring:
 profiles: WEBLOGIC
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: STO-GATEWAY
   backautenticacion: STO-BACK-AUTENTICACION
   backadministracion: STO-BACK-ADMINISTRACION
   frontautenticacion: STO-FRONT-AUTENTICACION
   frontadministracion: STO-FRONT-ADMINISTRACION
   frontconfiguracion: STO-FRONT-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:7001/authsto
 persistence:
  database: SQLSERVER_ORACLE
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true
