################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
server:
 port: 8080
 
spring:
 profiles: DES
 h2:
  console:
   path: /h2-console
 datasource:
  url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
  username: sa
  password:  
  driver-class-name: org.h2.Driver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
  
eureka:
 instance:    
  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION
  metadataMap:
   appOwner: STO
   description: API de administración del STO

---

################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
server:
 port: 8080
 
spring:
 profiles: LOCAL
 h2:
  console:
   path: /h2-console
   enabled: false
 datasource:
  url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
  username: sa
  password:  
  driver-class-name: org.h2.Driver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
 jpa:
  database: default
  
eureka:
 instance:    
#  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION
  metadataMap:
   appOwner: STO
   description: API de administración del STO

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'

# SqlServer DB - "OLD STO"
oldsto.datasource.url: jdbc:sqlserver://sqlsae2005.sadiel.es:1433;databaseName=BDSTO
oldsto.datasource.username: CEM_PRO_STO
oldsto.datasource.password: jkxcvjx34897534hjsdfh4
oldsto.datasource.driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
