################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
server:
 port: 9020
 servlet:
  context-path: /auth
  
spring:
 profiles: DES
 application:
  name: STO-BACK-AUTENTICACION
  
jwt:
 autenticacion:
  clientid: fooClientId
  clientsecret: $2a$10$O7WxkTdgBI7IWDh9.7nqOOam5wcTnE8G9Beyd.XCRBH4r/DmOuMjC
  accessTokenValidititySeconds: 120
  authorizedGrantTypes: password,authorization_code,refresh_token
  refreshTokenValiditySeconds: 240
  token:
   signing-key: 1234
   
config:
 seguridad:
   redirectUri:
    frontAutenticacion: http://172.18.3.124:8082
    frontAdministracion: http://172.18.3.124:8083
    frontConfiguracion: http://172.18.3.124:8889
    
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-BACK-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: API de autenticación del STO
   
---
################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
server:
 port: 9020
 servlet:
  context-path: /auth
  
spring:
 profiles: LOCAL
 h2:
  console:
   path: /h2-console
 datasource:
  url: jdbc:h2:mem:authDb;DB_CLOSE_DELAY=-1
  username: sa
  password:  
  driver-class-name: org.h2.Driver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-AUTENTICACION
  
jwt:
 autenticacion:
  token:
   signing-key: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
    
eureka:
 instance:
#  preferIpAddress: true
  virtualHostName: STO-BACK-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: API de autenticación del STO
