# Entorno del servidor de DESarrollo
server:
 port: 8083
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION

spring:
 profiles: DES
 application:
  name: STO-FRONT-ADMINISTRACION
  
eureka:
 instance:
  virtualHostName: STO-FRONT-ADMINISTRACION
  preferIpAddress: true
  metadataMap:
   appOwner: STO
   description: Front de administración  

---

# Entorno para desarrollo local
server:
 port: 8083
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION

spring:
 profiles: LOCAL
 application:
  name: STO-FRONT-ADMINISTRACION
  
eureka:
 instance:
  virtualHostName: STO-FRONT-ADMINISTRACION
  preferIpAddress: true
  metadataMap:
   appOwner: STO
   description: Front de administración  
