server:
 port: 9020
 servlet:
  context-path: /auth
  
spring:
 profiles: DES
 application:
  name: STO-BACK-AUTENTICACION
  
jwt:
 autenticacion:
  clientid: fooClientId
  clientsecret: $2a$10$O7WxkTdgBI7IWDh9.7nqOOam5wcTnE8G9Beyd.XCRBH4r/DmOuMjC
  accessTokenValidititySeconds: 120
  authorizedGrantTypes: password,authorization_code,refresh_token
  refreshTokenValiditySeconds: 240
  token:
   signing-key: 1234
   
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-BACK-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: API de autenticación del STO
