################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
server:
 port: 8082
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION
   
logging:
 file: /usr/local/nuevaarquitecturasto/logs/autenticacion-front.log

spring:
 profiles: DES
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: Front de autenticaci贸n del STO
   
# Configuraciones de seguridad
security:
 oauth2:
  client:
   clientId: stoAuthClientDes
   clientSecret: '{cipher}015d9f900e42352c30a084c8a5c8dd9860909876a31f8b0cb2b19e545d065cc8'
   accessTokenUri: ${config.endpoint.backautenticacion}/auth/oauth/token
   userAuthorizationUri: ${config.endpoint.backautenticacion}/auth/oauth/authorize
   clientAuthenticationScheme: form
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'

---

################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
server:
 port: 8082
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION
   
logging:
 file: D:/desarrollo/logs/autenticacion-front.log

spring:
 profiles: LOCAL
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
#  preferIpAddress: true
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: Front de autenticaci贸n del STO

# Configuraciones de seguridad
security:
 oauth2:
  client:
   clientId: stoAuthClientLocal
   clientSecret: '{cipher}015d9f900e42352c30a084c8a5c8dd9860909876a31f8b0cb2b19e545d065cc8'
   accessTokenUri: ${config.endpoint.backautenticacion}/auth/oauth/token
   userAuthorizationUri: ${config.endpoint.backautenticacion}/auth/oauth/authorize
   clientAuthenticationScheme: form
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
    
---

################################################################################################################################
# Entorno del servidor WEBLOGIC
################################################################################################################################
server:
 port: 7001
 servlet:
  context-path: ${config.server.context-paths.sto-front-autenticacion}
 session:
  cookie:
   name: UISESSION
   
logging:
 file: /usr/local/nuevaarquitecturasto/logs/autenticacion-front.log

spring:
 profiles: WEBLOGIC
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   configPath: ${config.server.context-paths.sto-front-autenticacion}
   appOwner: STO
   description: Front de autenticaci贸n del STO
   
# Configuraciones de seguridad
security:
 oauth2:
  client:
   clientId: stoAuthClientWeblogic
   clientSecret: '{cipher}015d9f900e42352c30a084c8a5c8dd9860909876a31f8b0cb2b19e545d065cc8'
   accessTokenUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/oauth/token
   userAuthorizationUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/oauth/authorize
   clientAuthenticationScheme: form
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'

---

################################################################################################################################
# Entorno del servidor TOMCAT
################################################################################################################################
server:
 port: 8001
 servlet:
  context-path: ${config.server.context-paths.sto-front-autenticacion}
 session:
  cookie:
   name: UISESSION
   
logging:
 file: /usr/local/nuevaarquitecturasto/logs/autenticacion-front.log

spring:
 profiles: TOMCAT
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   configPath: ${config.server.context-paths.sto-front-autenticacion}
   appOwner: STO
   description: Front de autenticaci贸n del STO
   
# Configuraciones de seguridad
security:
 oauth2:
  client:
   clientId: stoAuthClientTomcat
   clientSecret: '{cipher}015d9f900e42352c30a084c8a5c8dd9860909876a31f8b0cb2b19e545d065cc8'
   accessTokenUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/oauth/token
   userAuthorizationUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/oauth/authorize
   clientAuthenticationScheme: form
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
