################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
server:
 port: 9003
 servlet:
  context-path: ${config.server.context-paths.sto-back-administracion}
  
logging:
 file: /usr/local/nuevaarquitecturasto/logs/administracion-back.log
 
spring:
 profiles: DES
 datasource:
  url: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  jdbcUrl: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  username: sto
  password: sto
  driver-class-name: oracle.jdbc.OracleDriver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
  
eureka:
 instance:    
  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION -4545
  metadataMap:
   configPath: ${config.server.context-paths.sto-back-administracion}
   appOwner: STO
   description: API de administración del STO

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
    
config:
 cors:
  origins:
   backAdministracionOrigins: "*"

---

################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
server:
 port: 8080
 
logging:
 file: D:/desarrollo/logs/administracion-back.log
 
spring:
 profiles: LOCAL
 datasource:
  url: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  jdbcUrl: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  username: sto
  password: sto
  driver-class-name: oracle.jdbc.OracleDriver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
# jpa:
#  database: default
#  hibernate:
#   ddl-auto: update
  
eureka:
 instance:    
#  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION
  metadataMap:
   appOwner: STO
   description: API de administración del STO

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
    
general:
 persistence:
  database: SQLSERVER_ORACLE

# SqlServer DB - "OLD STO"
oldsto.datasource.url: jdbc:sqlserver://sqlsae2005.sadiel.es:1433;databaseName=BDSTO_TEST
oldsto.datasource.jdbcUrl: jdbc:sqlserver://sqlsae2005.sadiel.es:1433;databaseName=BDSTO_TEST
oldsto.datasource.username: CEM_PRO_STO
oldsto.datasource.password: jkxcvjx34897534hjsdfh4
oldsto.datasource.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

---

################################################################################################################################
# Entorno del servidor de Weblogic
################################################################################################################################
server:
 port: 7001
 servlet:
  context-path: ${config.server.context-paths.sto-back-administracion}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/administracion-back.log
 
spring:
 profiles: WEBLOGIC
 datasource:
  url: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  jdbcUrl: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  username: sto
  password: sto
  driver-class-name: oracle.jdbc.OracleDriver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
  
eureka:
 instance:    
  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION
  metadataMap:
   configPath: ${config.server.context-paths.sto-back-administracion}
   appOwner: STO
   description: API de administración del STO

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
    
config:
 cors:
  origins:
   backAdministracionOrigins: "*"

---

################################################################################################################################
# Entorno del servidor de TOMCAT
################################################################################################################################
server:
 port: 8001
 servlet:
  context-path: ${config.server.context-paths.sto-back-administracion}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/administracion-back.log
 
spring:
 profiles: TOMCAT
 datasource:
  url: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  jdbcUrl: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  username: sto
  password: sto
  driver-class-name: oracle.jdbc.OracleDriver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
  
eureka:
 instance:    
  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION
  metadataMap:
   configPath: ${config.server.context-paths.sto-back-administracion}
   appOwner: STO
   description: API de administración del STO

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'

---

################################################################################################################################
# Entorno del servidor de WEBLOGIC (SPRING CLOUD GATEWAY y LOAD BALANCER)
################################################################################################################################
server:
 port: 7001
 servlet:
  context-path: ${config.server.context-paths.sto-back-administracion}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/administracion-back.log
 
spring:
 profiles: WEBLOGIC-CLOUD-GATEWAY
 datasource:
  url: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  jdbcUrl: jdbc:oracle:thin:@172.18.1.33:1521:cartuja4
  username: sto
  password: sto
  driver-class-name: oracle.jdbc.OracleDriver
  sqlScriptEncoding: UTF-8
 application:
  name: STO-BACK-ADMINISTRACION
# Deshabilitar Ribbon para que use Spring Load Balancer (SPRING CLOUD GATEWAY)
 cloud:
  loadbalancer:
   ribbon:
    enabled: false
  
eureka:
 instance:    
  preferIpAddress: true
  virtualHostName: STO-BACK-ADMINISTRACION
  metadataMap:
   configPath: ${config.server.context-paths.sto-back-administracion}
   appOwner: STO
   description: API de administración del STO

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
    
config:
 cors:
  origins:
   backAdministracionOrigins: "*"
