# Entorno del servidor de DESarrollo
server:
 port: 8889
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION
   
spring:
 profiles: DES
 application:
  name: STO-FRONT-CONFIGURACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-CONFIGURACION
  metadataMap:
   appOwner: STO
   description: Front de configuración del STO
   
config:
 connecttimeout: 60000
 readtimeout: 3000
 
 ---
 
 # Entorno para desarrollo local
 server:
 port: 8889
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION
   
spring:
 profiles: LOCAL
 application:
  name: STO-FRONT-CONFIGURACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-CONFIGURACION
  metadataMap:
   appOwner: STO
   description: Front de configuración del STO
   
config:
 connecttimeout: 60000
 readtimeout: 3000

