server:
 port: 8082
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION

spring:
 profiles: DES
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: Front de autenticación del STO
