################################################################################################################################
# Entorno del servidor de DESarrollo
################################################################################################################################
server:
 port: 8082
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION

spring:
 profiles: DES
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: Front de autenticación del STO

---

################################################################################################################################
# Entorno para desarrollo LOCAL
################################################################################################################################
server:
 port: 8082
 servlet:
  context-path: /
 session:
  cookie:
   name: UISESSION

spring:
 profiles: LOCAL
 application:
  name: STO-FRONT-AUTENTICACION
  
eureka:
 instance:
  preferIpAddress: true
  virtualHostName: STO-FRONT-AUTENTICACION
  metadataMap:
   appOwner: STO
   description: Front de autenticación del STO
