################################################################################################################################
# Entorno del servidor de DESarrollo (ZUUL y RIBBON)
################################################################################################################################
server:
 port: 9002
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/gateway.log
 
spring:
 profiles: DES
 
# Discovery Server Access  
eureka:
 instance:
#  hostname: localhost
  virtualHostName: STO-GATEWAY
  preferIpAddress: true
  metadataMap:
   appOwner: STO
   description: Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'


zuul:
 host:
  connect-timeout-millis: 50000
  socket-timeout-millis: 50000
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  administracion:
   path: /administracion/**
   serviceId: STO-BACK-ADMINISTRACION
  configuracion:
   path: /configuracion/**
   serviceId: STO-BACK-CONFIGURACION
   
ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Gateway de STO
    version: 0.0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---

################################################################################################################################
# Entorno para desarrollo LOCAL (ZUUL y RIBBON)
################################################################################################################################
server:
 port: 9002
 
logging:
 file: D:/desarrollo/logs/gateway.log
 
spring:
 profiles: LOCAL
 
# Discovery Server Access  
eureka:
 instance:
  hostname: localhost
  virtualHostName: STO-GATEWAY
#  preferIpAddress: true
  metadataMap:
   appOwner: STO
   description: Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'

zuul:
 host:
  connect-timeout-millis: 50000
  socket-timeout-millis: 50000
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  administracion:
   path: /administracion/**
   serviceId: STO-BACK-ADMINISTRACION
  configuracion:
   path: /configuracion/**
   serviceId: STO-BACK-CONFIGURACION
   
ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Gateway de STO
    version: 0.0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---

################################################################################################################################
# Entorno del servidor de Weblogic (ZUUL y RIBBON)
################################################################################################################################
server:
 port: 7001
 servlet:
  context-path: ${config.server.context-paths.sto-gateway}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/gateway.log
 
spring:
 profiles: WEBLOGIC
 
# Discovery Server Access  
eureka:
 instance:
#  hostname: localhost
  virtualHostName: STO-GATEWAY
  preferIpAddress: true
  metadataMap:
   configPath: ${config.server.context-paths.sto-gateway}
   appOwner: STO
   description: Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'


zuul:
 host:
  connect-timeout-millis: 50000
  socket-timeout-millis: 50000
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  administracion:
   path: ${config.server.context-paths.sto-back-administracion}/**
   serviceId: STO-BACK-ADMINISTRACION
  configuracion:
   path: ${config.server.context-paths.sto-back-configuracion}/**
   serviceId: STO-BACK-CONFIGURACION
   
ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Gateway de STO
    version: 0.0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---

################################################################################################################################
# Entorno del servidor de TOMCAT (ZUUL y RIBBON)
################################################################################################################################
server:
 port: 8001
 servlet:
  context-path: ${config.server.context-paths.sto-gateway}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/gateway.log
 
spring:
 profiles: TOMCAT
 
# Discovery Server Access  
eureka:
 instance:
#  hostname: localhost
  virtualHostName: STO-GATEWAY
  preferIpAddress: true
  metadataMap:
   configPath: ${config.server.context-paths.sto-gateway}
   appOwner: STO
   description: Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'


zuul:
 host:
  connect-timeout-millis: 50000
  socket-timeout-millis: 50000
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  administracion:
   path: ${config.server.context-paths.sto-back-administracion}/**
   serviceId: STO-BACK-ADMINISTRACION
  configuracion:
   path: ${config.server.context-paths.sto-back-configuracion}/**
   serviceId: STO-BACK-CONFIGURACION
   
ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Gateway de STO
    version: 0.0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---
################################################################################################################################
# Entorno del servidor de DESarrollo (SPRING CLOUD GATEWAY y LOADBALANCER)
################################################################################################################################
server:
 port: 9002
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/spring-cloud-gateway.log
 
spring:
 profiles: DES-CLOUD-GATEWAY
# Routes
 cloud:
  gateway:
   routes[0]:
    id: STO-BACK-ADMINISTRACION
    uri: lb://STO-BACK-ADMINISTRACION
    predicates: Path=/administracion/**
    filters: StripPrefix=1
   routes[1]:
    id: STO-BACK-CONFIGURACION
    uri: lb://STO-BACK-CONFIGURACION
    predicates: Path=/configuracion/**
    filters: StripPrefix=1
# Deshabilitar Ribbon para que use Load Balancer
  loadbalancer:
   ribbon:
    enabled: false
 
# Discovery Server Access  
eureka:
 instance:
#  hostname: localhost
  virtualHostName: STO-GATEWAY
  preferIpAddress: true
  metadataMap:
   appOwner: STO
   description: Spring Cloud Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Spring Cloud Gateway de STO
    version: 0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---

################################################################################################################################
# Entorno para desarrollo LOCAL (SPRING CLOUD GATEWAY y LOADBALANCER)
################################################################################################################################
server:
 port: 9002
 
logging:
 file: D:/desarrollo/logs/spring-cloud-gateway.log
 
spring:
 profiles: LOCAL-CLOUD-GATEWAY
# Routes
 cloud:
  gateway:
   routes[0]:
    id: STO-BACK-ADMINISTRACION
    uri: lb://STO-BACK-ADMINISTRACION
    predicates: Path=/administracion/**
    filters: StripPrefix=1
   routes[1]:
    id: STO-BACK-CONFIGURACION
    uri: lb://STO-BACK-CONFIGURACION
    predicates: 
    - Path=/configuracion/**
    filters: 
    - StripPrefix=1
# Deshabilitar Ribbon para que use Load Balancer
  loadbalancer:
   ribbon:
    enabled: false
 
# Discovery Server Access  
eureka:
 instance:
  hostname: localhost
  virtualHostName: STO-GATEWAY
#  preferIpAddress: true
  metadataMap:
   appOwner: STO
   description: Spring Cloud Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}/auth/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'

# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Spring Cloud Gateway de STO
    version: 0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---

################################################################################################################################
# Entorno del servidor de Weblogic (SPRING CLOUD GATEWAY y LOADBALANCER)
################################################################################################################################
server:
 port: 7001
 servlet:
  context-path: ${config.server.context-paths.sto-gateway}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/spring-cloud-gateway.log
 
spring:
 profiles: WEBLOGIC-CLOUD-GATEWAY
# Routes
 cloud:
  gateway:
   routes[0]:
    id: STO-BACK-ADMINISTRACION
    uri: lb://STO-BACK-ADMINISTRACION
    predicates: Path=${config.server.context-paths.sto-back-administracion}/**
    filters: StripPrefix=1
   routes[1]:
    id: STO-BACK-CONFIGURACION
    uri: lb://STO-BACK-CONFIGURACION
    predicates: Path=${config.server.context-paths.sto-back-configuracion}/**
    filters: StripPrefix=1
# Deshabilitar Ribbon para que use Load Balancer
  loadbalancer:
   ribbon:
    enabled: false
 
# Discovery Server Access  
eureka:
 instance:
#  hostname: localhost
  virtualHostName: STO-GATEWAY
  preferIpAddress: true
  metadataMap:
   configPath: ${config.server.context-paths.sto-gateway}
   appOwner: STO
   description: Spring Cloud Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Spring Cloud Gateway de STO
    version: 0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}

---

################################################################################################################################
# Entorno del servidor de TOMCAT (SPRING CLOUD GATEWAY y LOADBALANCER)
################################################################################################################################
server:
 port: 8001
 servlet:
  context-path: ${config.server.context-paths.sto-gateway}
 
logging:
 file: /usr/local/nuevaarquitecturasto/logs/spring-cloud-gateway.log
 
spring:
 profiles: TOMCAT-CLOUD-GATEWAY
 
# Discovery Server Access  
eureka:
 instance:
#  hostname: localhost
  virtualHostName: STO-GATEWAY
  preferIpAddress: true
  metadataMap:
   configPath: ${config.server.context-paths.sto-gateway}
   appOwner: STO
   description: Spring Cloud Gateway de STO
 client:
  registerWithEureka: true
  fetch-registry: true

# Configuraciones de seguridad
security:
 oauth2:
  resource:
   userInfoUri: ${config.endpoint.backautenticacion}${config.server.context-paths.sto-back-autenticacion}/user/me
   preferTokenInfo: false
   jwt:
    key-value: '{cipher}63c159452c1099e88f1f681da4e1ac5352bb3cfc43225f3d73bb629c5166b4f6'
        
# Propiedades para actuator info
info:
  app:
    name: STO-GATEWAY
    description: Spring Cloud Gateway de STO
    version: 0.1-SNAPSHOT
  java-vendor: ${java.specification.vendor}
  java-version: ${java.vm.name}
