spring:
 profiles: des 
 h2:
  console:
   enabled: true
   path: /h2-console
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: create-drop
 datasource:
  url: jdbc:h2:mem:confDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: 
  driver-class-name: org.h2.Driver
  sqlScriptEncoding: UTF-8
  
# HTTP Server
server:
  port: 8888
  
# Configuración general
config:
 general:
  pagesize: 10
 endpoint:
  backautenticacion: http://localhost:9020
