server:
 port: 8080
 
spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 datasource:
  url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
  username: sa
  password:  
  driver-class-name: org.h2.Driver
 data:
  rest:
   base-path: /api
